version: "3.8"

services:
  web:
    build: .
    ports:
      # Maps port 8080 from container to host
      - "8080:8080"
    volumes:
      # Mount the source code for hot reloading
      - .:/app
      # Exclude node_modules from the mount (uses container's node_modules)
      - /app/node_modules
    environment:
      # Required for Vite's HMR to work properly in Docker
      - VITE_HOST=0.0.0.0
