name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose Services
        run: |
          docker compose up -d web selenium
          # Wait for services to be healthy
          timeout 60s bash -c 'until docker compose ps | grep -q "healthy"; do sleep 1; done'

      - name: Create Target Directory
        run: mkdir -p target

      - name: Run Tests
        run: |
          # Run tests and mount the target directory to capture results directly
          docker compose run --rm \
            -v "$(pwd)/target:/app/target" \
            tests mvn test -Dsurefire.useFile=false

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/site/
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 30
